#!/usr/bin/env ruby
#
# This file is part of "sema".
#
# (c) Konstantinos Gerodimos <kosta@gerodimos.com>
#
# This source file is subject to the Apache License that is bundled
# with this source code in the file LICENSE.
#

# Load bootstrap
require "#{Dir.pwd}/lib/sema"

VERSION = "v1.0 pre-alpha"

def extract(input_text)

	# Instatiate Semantic Extractor
  print "Extracting..."
  time = Benchmark.realtime { @sema = Semantic::Extractor.new(input_text) }
  print "DONE! (#{time}s)\n"
  
end

def show_analysis
  puts
  puts "======================="
  puts "Sentences: " + @sema.sentences.count.to_s
  puts "Words: " + @sema.words.count.to_s
  puts "======================="
  puts

  for sentence in @sema.sentences
    
    for word in @sema.sentence(sentence.position)

      t = 'unknown' if word.class.nil?
      t = word.class if word.class

      if word.punctuation.nil?
        print "[#{t} => #{word.text}]" + " "
      else
        print "[#{t} => #{word.text}]" + "[#{word.punctuation}] "
      end
    end
    print "\n"
    puts
  end
end

def show_text

  puts
  for sentence in @sema.sentences
    
    for word in @sema.sentence(sentence.position)

      t = 'unknown' if word.class.nil?
      t = word.class if word.class

      if word.punctuation.nil?
        print "#{word.text}" + " "
      else
        print "#{word.text}" + "[#{word.punctuation}] "
      end
    end
    print "\n"
    puts
  end
end

def show_input
  puts
  puts @input_text
  puts
end

def list_words

  puts
  for word in @sema.words
    puts "#{word.position} [#{word.text}], [#{word.class}]"
  end
  puts

end

def list_learn

  puts
  for word in @sema.words
    puts "#{word.position} [#{word.text}], [#{word.class}]" if word.class.nil? or word.class == 'unclassified'
  end
  puts

end

def list_class(classification)

  puts
  for word in @sema.words
    puts "#{word.position} [#{word.text}], [#{word.class}]" if word.class == classification
  end
  puts

end

def version
	puts
	puts "SEMA #{VERSION}"
	puts
end

version

loop do
  ('sema %> ').display
  input = gets.chomp
  command, *params = input.split /\s/
  case command
    when 'help'

      puts
      puts "Commands: help, exit, version, read, load, show, stem, plural, singular, find, sfind, list, learn, add, unlearn, extract"
      puts

    when 'exit'

    	exit

    when 'version'

    	version

    when 'read'

      puts
    	('input text : ').display
    	@input_text = gets.chomp
      puts

      extract(@input_text)
      puts

    when 'load'

      @input_text = File.open("#{Dir.pwd}/input.txt").read
      show_input

      extract(@input_text)
      puts

    when 'extract'

      puts
      extract(@input_text)
      puts

    when 'show'

      case params.first
      when 'text'
        show_text
      when 'input'
        show_input
      else
        show_analysis
      end

    when 'stem'

      puts
      puts Syntactic::Stem.word(params.first)
      puts

    when 'plural'

      puts
    	puts params.first.pluralize
      puts

    when 'singular'

      puts
    	puts params.first.singularize
      puts

    when 'find'

      puts
    	word = Syntactic::Find.basic(params.first).first
    	pp word unless word.nil?
      puts

    when 'sfind'

      puts
      found = Syntactic::Find.stem(params.first)

      pp found.first

      words = found.to_a
      if words.count != 0
        for word in words
          pp word.classifications.to_a
        end
      end
      puts

    when 'learn'

      pp Syntactic::Learn.word(params.first)

    when 'add'

      pp Syntactic::Learn.classification(params[0], params[1], params[2])

    when 'unlearn'

      pp Syntactic::Unlearn.by_id(params[0])

    when 'list'

      case params.first
      when 'words'
        list_words
      when 'learn'
        list_learn
      when 'class'
        list_class params[1]
      end

    else
      
      puts
      puts 'Invalid command'
      puts

  end
end